### ISSUE TITLE
examples fails with latest update for bb key needed

### ISSUE THREAD

**Issue by TermeHansen** [bernhard-42/cad-viewer-widget#2]
some examples with version 1.3.2 and it fails with 

here for instance "box"

```
File ~/miniforge3/envs/cad/lib/python3.10/site-packages/cad_viewer_widget/widget.py:681, in CadViewer.add_shapes(self, shapes, states, tracks, normal_len, default_edge_color, default_opacity, ambient_intensity, direct_intensity, tools, glass, cad_width, tree_width, height, control, ortho, axes, axes0, grid, ticks, transparent, black_edges, collapse, position, quaternion, target, zoom, reset_camera, zoom_speed, pan_speed, rotate_speed, timeit, js_debug)
    678         print("Camera control changed, so camera was resetted")
    680 if reset_camera:
--> 681     center, radius = bsphere(shapes["bb"])
    683     if position is None:
    684         position = (normalize(np.array((1, 1, 1))) * 5.5 * radius + center).tolist()

KeyError: 'bb'
```

but even when changing to only showing the first part I don't see anything in the viewer??

![image](https://user-images.githubusercontent.com/6922018/165516236-9cc9e340-835b-4c2b-84bd-024ef50ed654.png)

**Comment by bernhard-42** [comment]
@TermeHansen I have changed the internal format of the tesselation files slightly: Instead of having a bounding box ("bb") per assembly object, now only one overall bounding box is needed on the top-level. This is due to the change in the underlying three-cad-viewer project.

So it is important to install `cad-viewer-widget 1.3.2` and pull the latest git repo with the examples.

Additionally, I forgot to migrate the examples `box.json` and `longbox.json`. This is fixed in the latest commit.
